server:
  port: 8088

spring:
  application:
    name: api-gateway
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
        - id: fraud
          uri: lb://FRAUD
          predicates:
            - Path=/api/v1/fraud/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true


management:
  tracing:
    sampling:
      probability: 1.0   # trace every request (dev)