server:
  port: 8088

spring:
  application:
    name: api-gateway
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
        - id: fraud
          uri: lb://FRAUD
          predicates:
            - Path=/api/v1/fraud/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    ip-address: 192.168.100.31   # replace with your host machine IP
    #    hostname: fraud-server       # optional, can be ignored
    instance-id: ${spring.application.name}:${server.port}

management:
  tracing:
    sampling:
      probability: 1.0   # trace every request (dev)